server:
  port: 1111

eureka:
  datacenter: SpringCloud
  environment: ${EUREKA_ENVIRONMENT:prod}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl.defaultZone: http://machinedog.yipzale.me:${server.port}/eureka/
  server:
    responseCacheUpdateInvervalMs: 3000
    eviction-interval-timer-in-ms: 3000